# Aula 3 - Composição da desocupação por sexo (2012 x 2026) cruzada com afazeres domésticos

Nesta aula:
1. Abrimos e juntamos as duas **Tabelas 5** (composição da desocupação por sexo, 2012 e 2026)
2. Comparamos ano a ano (variação em pontos percentuais)
3. Cruzamos com a **Tabela 1.1.1** do IBGE (horas semanais de cuidados/afazeres domésticos, 2022), tratada do mesmo jeito que na Aula 2

In [1]:
import pandas as pd

## 1) Ler e juntar as duas Tabelas 5 (2012 e 2026)

In [2]:
t2012 = pd.read_csv(
    "Tabela5-sem_emprego_2012.csv",
    sep=";", decimal=",", encoding="utf-8-sig"
)
t2026 = pd.read_csv(
    "Tabela5-sem_emprego_2026.csv",
    sep=";", decimal=",", encoding="utf-8-sig"
)

comp = t2012.merge(t2026, on=["Sigla", "Código", "Estado"], how="inner")
comp.head()

,Sigla,Código,Estado,Desocupados - homens (2012 T1),Desocupados - mulheres (2012 T1),Desocupados - homens (2026 T1),Desocupados - mulheres (2026 T1)
0,AC,12,Acre,45.3,54.7,53.2,46.8
1,AL,27,Alagoas,44.7,55.3,50.7,49.3
2,AM,13,Amazonas,47.5,52.5,46.8,53.2
3,AP,16,Amapá,48.1,51.9,51.1,48.9
4,BA,29,Bahia,43.8,56.2,44.7,55.3

## 2) Comparar ano a ano (variação 2026 - 2012, em pontos percentuais)

In [3]:
comp["Var. homens (p.p.)"] = (
    comp["Desocupados - homens (2026 T1)"] - comp["Desocupados - homens (2012 T1)"]
).round(1)
comp["Var. mulheres (p.p.)"] = (
    comp["Desocupados - mulheres (2026 T1)"] - comp["Desocupados - mulheres (2012 T1)"]
).round(1)

comp = comp.sort_values("Var. mulheres (p.p.)")
comp

,Sigla,Código,Estado,Desocupados - homens (2012 T1),Desocupados - mulheres (2012 T1),Desocupados - homens (2026 T1),Desocupados - mulheres (2026 T1),Var. homens (p.p.),Var. mulheres (p.p.)
0,AC,12,Acre,45.3,54.7,53.2,46.8,7.9,-7.9
6,DF,53,Distrito Federal,41.0,59.0,47.9,52.1,6.9,-6.9
8,GO,52,Goiás,41.0,59.0,47.5,52.5,6.5,-6.5
1,AL,27,Alagoas,44.7,55.3,50.7,49.3,6.0,-6.0
17,PR,41,Paraná,40.3,59.7,46.3,53.7,6.0,-6.0
10,MG,31,Minas Gerais,43.1,56.9,48.6,51.4,5.5,-5.5
13,PA,15,Pará,43.2,56.8,48.3,51.7,5.1,-5.1
15,PE,26,Pernambuco,43.9,56.1,48.7,51.3,4.8,-4.8
22,RS,43,Rio Grande do Sul,42.8,57.2,47.4,52.6,4.6,-4.6
14,PB,25,Paraíba,44.4,55.6,48.9,51.1,4.5,-4.5
16,PI,22,Piauí,51.2,48.8,55.1,44.9,3.9,-3.9
3,AP,16,Amapá,48.1,51.9,51.1,48.9,3.0,-3.0
23,SC,42,Santa Catarina,42.7,57.3,44.6,55.4,1.9,-1.9
9,MA,21,Maranhão,47.2,52.8,49.1,50.9,1.9,-1.9
5,CE,23,Ceará,51.1,48.9,52.7,47.3,1.6,-1.6
21,RR,14,Roraima,41.8,58.2,43.4,56.6,1.6,-1.6
18,RJ,33,Rio de Janeiro,44.2,55.8,45.4,54.6,1.2,-1.2
7,ES,32,Espírito Santo,46.4,53.6,47.5,52.5,1.1,-1.1
4,BA,29,Bahia,43.8,56.2,44.7,55.3,0.9,-0.9
25,SP,35,São Paulo,45.4,54.6,46.2,53.8,0.8,-0.8
2,AM,13,Amazonas,47.5,52.5,46.8,53.2,-0.7,0.7
12,MT,51,Mato Grosso,44.1,55.9,42.8,57.2,-1.3,1.3
11,MS,50,Mato Grosso do Sul,47.2,52.8,45.3,54.7,-1.9,1.9
19,RN,24,Rio Grande do Norte,51.0,49.0,48.2,51.8,-2.8,2.8
24,SE,28,Sergipe,46.5,53.5,40.3,59.7,-6.2,6.2
26,TO,17,Tocantins,55.3,44.7,46.2,53.8,-9.1,9.1
20,RO,11,Rondônia,43.4,56.6,33.0,67.0,-10.4,10.4

## 3) Ler a Tabela 1.1.1 do IBGE (aba 2022) — mesmo tratamento da Aula 2

- pula as 8 primeiras linhas (título + cabeçalho em várias linhas)
- nomeia as colunas na mão
- remove linhas de Grandes Regiões / Brasil / rodapé de fonte e notas

In [4]:
colunas = [
    "Estado",
    "Horas - total",
    "Horas - total (brancos)",
    "Horas - total (pretos/pardos)",
    "Horas - homens (brancos)",
    "Horas - homens (pretos/pardos)",
    "Horas - mulheres (brancas)",
    "Horas - mulheres (pretas/pardas)",
]

tab111 = pd.read_excel(
    "Tabela_1_1_1__1_.xls",
    sheet_name="2022",
    header=None,
    skiprows=8,
    names=colunas,
)

grandes_regioes = ["Brasil", "Norte", "Nordeste", "Sudeste", "Sul", "Centro-Oeste"]
tab111 = tab111.dropna(subset=["Estado"])
tab111 = tab111[~tab111["Estado"].isin(grandes_regioes)]
tab111 = tab111[pd.to_numeric(tab111["Horas - total"], errors="coerce").notna()]

# médias simples homens / mulheres (branco + preto ou pardo)
tab111["Horas - homens"] = tab111[["Horas - homens (brancos)", "Horas - homens (pretos/pardos)"]].mean(axis=1).round(2)
tab111["Horas - mulheres"] = tab111[["Horas - mulheres (brancas)", "Horas - mulheres (pretas/pardas)"]].mean(axis=1).round(2)
tab111["Horas - total"] = tab111["Horas - total"].round(2)

tab111.head()

,Estado,Horas - total,Horas - total (brancos),Horas - total (pretos/pardos),Horas - homens (brancos),Horas - homens (pretos/pardos),Horas - mulheres (brancas),Horas - mulheres (pretas/pardas),Horas - homens,Horas - mulheres
2,Rondônia,17.01,16.727733,17.101523,12.111127,12.544080,20.412887,21.061410,12.33,20.74
3,Acre,13.61,13.806929,13.541399,10.796120,9.686983,16.130352,16.710754,10.24,16.42
4,Amazonas,16.81,15.987545,16.995493,12.233043,12.822584,18.764969,20.716986,12.53,19.74
5,Roraima,13.64,13.651755,13.633606,10.814803,10.476601,16.135877,16.560244,10.65,16.35
6,Pará,16.47,16.181627,16.560239,11.524306,11.026707,19.835110,21.591144,11.28,20.71

## 4) Dar Sigla/Código à Tabela 1.1.1

A Tabela 1.1.1 só traz o nome do estado. Usamos o de-para que já existe em `comp` (mesmos nomes de Estado das Tabelas 5) para trazer Sigla e Código.

In [5]:
de_para = comp[["Sigla", "Código", "Estado"]]
tab111 = de_para.merge(tab111, on="Estado", how="inner")
tab111.head()

,Sigla,Código,Estado,Horas - total,Horas - total (brancos),Horas - total (pretos/pardos),Horas - homens (brancos),Horas - homens (pretos/pardos),Horas - mulheres (brancas),Horas - mulheres (pretas/pardas),Horas - homens,Horas - mulheres
0,AC,12,Acre,13.61,13.806929,13.541399,10.796120,9.686983,16.130352,16.710754,10.24,16.42
1,DF,53,Distrito Federal,15.10,15.061306,15.126295,11.377952,10.481279,17.738123,19.307332,10.93,18.52
2,GO,52,Goiás,15.19,14.962622,15.296966,10.636424,10.531883,18.440842,19.587913,10.58,19.01
3,AL,27,Alagoas,20.22,19.165111,20.560451,12.121839,13.357160,24.093655,25.856637,12.74,24.98
4,PR,41,Paraná,15.39,15.453295,15.307289,11.240085,10.815611,18.896661,19.365380,11.03,19.13

## 5) Cruzar a comparação de desocupação com a Tabela 1.1.1

In [6]:
cruzado = comp.merge(tab111, on=["Sigla", "Código", "Estado"], how="inner")
cruzado

,Sigla,Código,Estado,Desocupados - homens (2012 T1),Desocupados - mulheres (2012 T1),Desocupados - homens (2026 T1),Desocupados - mulheres (2026 T1),Var. homens (p.p.),Var. mulheres (p.p.),Horas - total,Horas - total (brancos),Horas - total (pretos/pardos),Horas - homens (brancos),Horas - homens (pretos/pardos),Horas - mulheres (brancas),Horas - mulheres (pretas/pardas),Horas - homens,Horas - mulheres
0,AC,12,Acre,45.3,54.7,53.2,46.8,7.9,-7.9,13.61,13.806929,13.541399,10.796120,9.686983,16.130352,16.710754,10.24,16.42
1,DF,53,Distrito Federal,41.0,59.0,47.9,52.1,6.9,-6.9,15.10,15.061306,15.126295,11.377952,10.481279,17.738123,19.307332,10.93,18.52
2,GO,52,Goiás,41.0,59.0,47.5,52.5,6.5,-6.5,15.19,14.962622,15.296966,10.636424,10.531883,18.440842,19.587913,10.58,19.01
3,AL,27,Alagoas,44.7,55.3,50.7,49.3,6.0,-6.0,20.22,19.165111,20.560451,12.121839,13.357160,24.093655,25.856637,12.74,24.98
4,PR,41,Paraná,40.3,59.7,46.3,53.7,6.0,-6.0,15.39,15.453295,15.307289,11.240085,10.815611,18.896661,19.365380,11.03,19.13
5,MG,31,Minas Gerais,43.1,56.9,48.6,51.4,5.5,-5.5,17.50,17.179387,17.707564,11.319720,11.619120,22.186650,23.075751,11.47,22.63
6,PA,15,Pará,43.2,56.8,48.3,51.7,5.1,-5.1,16.47,16.181627,16.560239,11.524306,11.026707,19.835110,21.591144,11.28,20.71
7,PE,26,Pernambuco,43.9,56.1,48.7,51.3,4.8,-4.8,19.31,18.950219,19.418444,12.312833,12.868821,23.357880,24.243396,12.59,23.80
8,RS,43,Rio Grande do Sul,42.8,57.2,47.4,52.6,4.6,-4.6,15.36,15.337269,15.448203,11.308447,11.519941,18.868230,19.107720,11.41,18.99
9,PB,25,Paraíba,44.4,55.6,48.9,51.1,4.5,-4.5,18.92,18.887920,18.945306,12.480204,12.400831,23.642936,24.035650,12.44,23.84
10,PI,22,Piauí,51.2,48.8,55.1,44.9,3.9,-3.9,17.96,16.948094,18.231789,12.258324,11.204814,20.494063,23.695440,11.73,22.09
11,AP,16,Amapá,48.1,51.9,51.1,48.9,3.0,-3.0,13.59,14.389180,13.415091,11.116821,10.749444,16.648579,15.908487,10.93,16.28
12,SC,42,Santa Catarina,42.7,57.3,44.6,55.4,1.9,-1.9,16.04,16.124417,15.616235,12.339052,11.517342,19.414764,19.646573,11.93,19.53
13,MA,21,Maranhão,47.2,52.8,49.1,50.9,1.9,-1.9,16.67,16.421773,16.708894,11.665173,11.437359,19.881056,20.739589,11.55,20.31
14,CE,23,Ceará,51.1,48.9,52.7,47.3,1.6,-1.6,19.50,18.527120,19.882469,12.186936,12.821323,23.019718,24.952274,12.50,23.99
15,RR,14,Roraima,41.8,58.2,43.4,56.6,1.6,-1.6,13.64,13.651755,13.633606,10.814803,10.476601,16.135877,16.560244,10.65,16.35
16,RJ,33,Rio de Janeiro,44.2,55.8,45.4,54.6,1.2,-1.2,16.72,16.097467,17.243060,12.000036,12.864896,19.203741,20.957728,12.43,20.08
17,ES,32,Espírito Santo,46.4,53.6,47.5,52.5,1.1,-1.1,17.11,16.510610,17.478861,11.798571,12.017589,20.464462,22.196626,11.91,21.33
18,BA,29,Bahia,43.8,56.2,44.7,55.3,0.9,-0.9,17.85,17.538007,17.935566,10.551673,10.982808,22.572730,23.217119,10.77,22.89
19,SP,35,São Paulo,45.4,54.6,46.2,53.8,0.8,-0.8,17.07,16.964437,17.255480,12.123044,12.235200,20.771186,21.767620,12.18,21.27
20,AM,13,Amazonas,47.5,52.5,46.8,53.2,-0.7,0.7,16.81,15.987545,16.995493,12.233043,12.822584,18.764969,20.716986,12.53,19.74
21,MT,51,Mato Grosso,44.1,55.9,42.8,57.2,-1.3,1.3,14.24,14.083513,14.270209,9.479654,9.265734,17.782825,18.695923,9.37,18.24
22,MS,50,Mato Grosso do Sul,47.2,52.8,45.3,54.7,-1.9,1.9,15.31,14.902105,15.567204,10.446213,11.126920,18.593200,19.542761,10.79,19.07
23,RN,24,Rio Grande do Norte,51.0,49.0,48.2,51.8,-2.8,2.8,18.31,18.101853,18.445218,11.166909,11.086286,23.547080,24.422884,11.13,23.98
24,SE,28,Sergipe,46.5,53.5,40.3,59.7,-6.2,6.2,18.83,17.264294,19.317934,10.830511,11.270341,21.740902,25.637681,11.05,23.69
25,TO,17,Tocantins,55.3,44.7,46.2,53.8,-9.1,9.1,15.82,15.701788,15.768728,10.733863,11.682616,19.663713,19.629399,11.21,19.65
26,RO,11,Rondônia,43.4,56.6,33.0,67.0,-10.4,10.4,17.01,16.727733,17.101523,12.111127,12.544080,20.412887,21.061410,12.33,20.74

## 6) Salvar resultados

No seu PC, troque o caminho por algo como `r"H:\dados30\python-tecTI\dados\geral.csv"`.

In [7]:
comp.to_csv("comp_2012_2026.csv", sep=";", decimal=",", index=False)
cruzado.to_csv("geral.csv", sep=";", decimal=",", index=False)

## 7) Alguns achados rápidos

In [8]:
print("Média nacional 2012 - homens/mulheres:", comp["Desocupados - homens (2012 T1)"].mean().round(1), comp["Desocupados - mulheres (2012 T1)"].mean().round(1))
print("Média nacional 2026 - homens/mulheres:", comp["Desocupados - homens (2026 T1)"].mean().round(1), comp["Desocupados - mulheres (2026 T1)"].mean().round(1))
print()
print("Correlação Var. mulheres (p.p.) x Horas - mulheres:", cruzado["Var. mulheres (p.p.)"].corr(cruzado["Horas - mulheres"]).round(3))

Média nacional 2012 - homens/mulheres: 45.4 54.6
Média nacional 2026 - homens/mulheres: 47.0 53.0

Correlação Var. mulheres (p.p.) x Horas - mulheres: 0.103